# Generated by Django 2.2.2 on 2019-07-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
